compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  "eslint-plugin-storybook@*":
    dependencies:
      typescript: 5.6.3
  "@storybook/react-vite@*":
    dependencies:
      typescript: 5.6.3
  "@storybook/addon-onboarding@*":
    dependencies:
      react: 18.3.1
  "@storybook/addon-docs@*":
    dependencies:
      "@types/react": 18.3.17
  "@chromatic-com/storybook@*":
    dependencies:
      react: 18.3.1

